#!/usr/bin/env python

import gtk
import os
import sys

# Internationalization
import locale
import gettext
import gtk.glade
gettext.bindtextdomain("gtkusersetup", "/usr/share/locale")
gettext.textdomain("gtkusersetup")
gettext.install("gtkusersetup", "/usr/share/locale", unicode=1)
gtk.glade.bindtextdomain("gtkusersetup", "/usr/share/locale")
gtk.glade.textdomain("gtkusersetup")

class GTKUserSetup:
	def on_button_close_clicked(self, widget, data=None):
		gtk.main_quit()

	def gtk_main_quit(self, widget, data=None):
		gtk.main_quit()

	def __init__(self):
		builder = gtk.Builder()
		if os.path.exists('gtkusersetup.glade'):
			builder.add_from_file('gtkusersetup.glade')
		elif os.path.exists('/usr/share/salixtools/gtkusersetup/gtkusersetup.glade'):
			builder.add_from_file('/usr/share/salixtools/gtkusersetup/gtkusersetup.glade')
		self.window = builder.get_object('gtkusersetup')
		self.namecolumn = builder.get_object('namecolumn')
		self.logincolumn = builder.get_object('logincolumn')
		self.homedircolumn = builder.get_object('homedircolumn')
		self.userlist = builder.get_object('userlist')
		self.userliststore = builder.get_object('userliststore')
		builder.connect_signals(self)

		self.namecolumn.set_title(_('Name'))
		self.logincolumn.set_title(_('Login name'))
		self.homedircolumn.set_title(_('Home directory'))

if __name__ == "__main__":
	app = GTKUserSetup()
	app.window.show()
	gtk.main()
