#!/usr/bin/env python
# vim:et:sta:sts=4:sw=4:ts=8:tw=79:

import commands
import gtk
import os
import sys
import subprocess

# Internationalization
import locale
import gettext
locale.setlocale(locale.LC_ALL, '')
locale.bindtextdomain("gtkreposetup", "/usr/share/locale")
gettext.bindtextdomain("gtkreposetup", "/usr/share/locale")
gettext.textdomain("gtkreposetup")
_ = gettext.gettext

class GTKRepoSetup:

    def on_button_about_clicked(self, widget, data=None):
        self.aboutdialog.show()

    def on_aboutdialog_response(self, widget, data=None):
        self.aboutdialog.hide()

    def on_aboutdialog_delete_event(self, widget, event):
        self.aboutdialog.hide()
        return True

    def on_button_ok_clicked(self, widget, data=None):
        
        gtk.main_quit()

    def on_button_cancel_clicked(self, widget, data=None):
        gtk.main_quit()

    def on_gtkreposetup_delete_event(self, widget, event):
        gtk.main_quit()

    def gtk_main_quit(self, widget, data=None):
        gtk.main_quit()

    def __init__(self):
        builder = gtk.Builder()
        builder.set_translation_domain("gtkreposetup")
        if os.path.exists('gtkreposetup.glade'):
            builder.add_from_file('gtkreposetup.glade')
        elif os.path.exists('/usr/share/salixtools/gtkreposetup/gtkreposetup.glade'):
            builder.add_from_file(
                '/usr/share/salixtools/gtkreposetup/gtkreposetup.glade')
        self.window = builder.get_object('gtkreposetup')
        self.aboutdialog = builder.get_object('aboutdialog')

        builder.connect_signals(self)
        self.repolist = builder.get_object('repolist')
        self.liststore_repo = builder.get_object('liststore_repo')
        self.liststore_repo.clear()

if __name__ == "__main__":
    app = GTKRepoSetup()
    app.window.show()
    gtk.main()
