#!/usr/bin/env python

import commands
import gtk
import os
import sys

# Internationalization
import locale
import gettext
import gtk.glade
gettext.bindtextdomain("gtkkeyboardsetup", "/usr/share/locale")
gettext.textdomain("gtkkeyboardsetup")
gettext.install("gtkkeyboardsetup", "/usr/share/locale", unicode=1)
gtk.glade.bindtextdomain("gtkkeyboardsetup", "/usr/share/locale")
gtk.glade.textdomain("gtkkeyboardetup")

def getkeymap():
	keymap = 'us'
	f = file('/etc/rc.d/rc.keymap')
	while True:
		line = f.readline().replace('\n', '').lstrip(' ')
		if len(line) == 0:
			break
		if line.startswith('/usr/bin/loadkeys'):
			keymap = line.lstrip('/usr/bin/loadkeys ').rstrip('.map')
	f.close()
	return keymap

def getnumlock():
	numlock = False
	if os.access('/etc/rc.d/rc.numlock', os.X_OK):
		numlock = True
	return numlock

def getscim():
	scim = False
	if os.access('/usr/bin/scim', os.X_OK):
		if os.access('/etc/profile.d/scim.sh', os.X_OK):
			scim = True
	return scim

class GTKKeyboardSetup:
	def on_button_ok_clicked(self, widget, data=None):
		gtk.main_quit()

	def on_button_cancel_clicked(self, widget, data=None):
		gtk.main_quit()
	
	def gtk_main_quit(self, widget, data=None):
		gtk.main_quit()
	
	def __init__(self):
		builder = gtk.Builder()
		if os.path.exists('gtkkeyboardsetup.glade'):
			builder.add_from_file('gtkkeyboardsetup.glade')
		elif os.path.exists('/usr/share/salixtools/gtkkeyboardsetup/gtkkeyboardsetup.glade'):
			builder.add_from_file('/usr/share/salixtools/gtkkeyboardsetup/gtkkeyboardsetup.glade')
		self.window = builder.get_object('gtkkeyboardsetup')

		builder.connect_signals(self)
		self.localelist = builder.get_object('keymaplist')
		self.localeliststore = builder.get_object('keymapliststore')
		#self.localeliststore.clear()

if __name__ == "__main__":
	app = GTKKeyboardSetup()
	app.window.show()
	gtk.main()
