#!/usr/bin/env python

import commands
import gtk
import os
import sys

# Internationalization
import gtk.glade
gtk.glade.bindtextdomain("gtkservicesetup", "/usr/share/locale")
gtk.glade.textdomain("gtkservicesetup")

def blacklistedservices():
	f = file('/usr/share/salixtools/servicesetup/service-blacklist')
	for i in f:
		print i
	f.close()

def availableservices():
	filelist = os.listdir('/etc/rc.d')
	services = []
	for i in filelist:
		if i.startswith('rc.'):
			print i

class GTKServiceSetup:
	def on_button_ok_clicked(self, widget, data=None):
		availableservices()
		print 'BLACKLISTED'
		blacklistedservices()
		gtk.main_quit()

	def on_button_cancel_clicked(self, widget, data=None):
		gtk.main_quit()
	
	def on_checkbox_toggled(self, widget, data=None):
		selectedservice = self.serviceslist.get_selection()
		self.servicesliststore, iter = selectedservice.get_selected()
		selectedservicename =  self.servicesliststore.get_value(iter, 1)
		for i in self.servicesliststore:
			if i[1] == selectedservicename:
				if i[0] == 0:
					i[0] = 1
				else:
					i[0] = 0

	def gtk_main_quit(self, widget, data=None):
		gtk.main_quit()
	
	def __init__(self):
		builder = gtk.Builder()
		if os.path.exists('gtkservicesetup.glade'):
			builder.add_from_file('gtkservicesetup.glade')
		elif os.path.exists('/usr/share/salixtools/gtkservicesetup/gtkservicesetup.glade'):
			builder.add_from_file('/usr/share/salixtools/gtkservicesetup/gtkservicesetup.glade')
		self.window = builder.get_object('gtkservicesetup')

		builder.connect_signals(self)
		self.serviceslist = builder.get_object('serviceslist')
		self.servicesliststore = builder.get_object('servicesliststore')
		self.servicesliststore.clear()
		self.servicesliststore.append([1, 'foo', 'The foo service'])
		self.servicesliststore.append([0, 'bar', 'The bar service'])
		self.servicesliststore.append([1, 'zoom', 'The zoom service'])

if __name__ == "__main__":
	app = GTKServiceSetup()
	app.window.show()
	gtk.main()
